name: Update Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: liberti1991
          svg_out_path: snake.svg
          gif_out_path: false  # Desativa a geração de GIF

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: snake.svg
          message: 'Update snake animation'
          branch: main
